name: Test Build Every 5 Minutes

on:
  schedule:
    # Runs every 5 minutes (for testing purposes)
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '21' # Adjust to your JDK version

    - name: Run Tests
      run: ./gradlew test

    - name: Build Application
      run: ./gradlew build
