name: Test Build Every 5 Minutes

on:
  schedule:
    # Runs every 5 minutes (for testing purposes)
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: T3dev # Check out the `dev` branch

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '21' # Adjust to your JDK version

    - name: Build Application
      run: ./gradlew build

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: T3dev # Check out the `dev` branch
        
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Run tests
      run: ./gradlew test

    
